SET NAMES 'utf8' COLLATE 'utf8_general_ci';

INSERT INTO `word_annotation_types` VALUES (1,'lexeme',0,0,'glossing - lexical information'), (2,'grammar',1,1,'glossing - grammatical information'), (3,'POS',1,0,'part of speech'),(4,'syntax',1,0,'syntactic information'),(5,'semantics',1,0,'semantic information'),(6,'pragmatic',1,0,'pragmatic information');

INSERT INTO `word_annotation_type_choices` VALUES (1,'1',2,'first person'), (2,'2',2,'second person'), (3,'3',2,'third person'), (4,'ABL',2,'ablative'), (5,'ABS',2,'absolutive'), (6,'ACC',2,'accusative'), (7,'AGR',2,'agreement'), (8,'ALL',2,'allative'), (9,'ANTIP',2,'antipassive'), (10,'APPL',2,'applicative'), (11,'ART',2,'article'), (12,'AUX',2,'auxiliary'), (13,'BEN',2,'benefactive'), (14,'CAUS',2,'causative'), (15,'CLF',2,'classifier'), (16,'COM',2,'comitative'), (17,'COMP',2,'complementizer'), (18,'COMPL',2,'completive'), (19,'COND',2,'conditional'), (20,'COP',2,'copula'), (21,'CVB',2,'converb'), (22,'DAT',2,'dative'), (23,'DECL',2,'declarative'), (24,'DEF',2,'definite'), (25,'DEM',2,'demonstrative'), (26,'DET',2,'determiner'), (27,'DIST',2,'distal'), (28,'DISTR',2,'distributive'), (29,'DU',2,'dual'), (30,'DUR',2,'durative'), (31,'ERG',2,'ergative'), (32,'EXCL',2,'exclusive'), (33,'F',2,'feminine'), (34,'FOC',2,'focus'), (35,'FUT',2,'future'), (36,'GEN',2,'genitive'), (37,'IMP',2,'imperative'), (38,'INCL',2,'inclusive'), (39,'IND',2,'indicative'), (40,'INDF',2,'indefinite'), (41,'INF',2,'infinitive'), (42,'INS',2,'instrumental'), (43,'INTR',2,'intransitive'), (44,'IPFV',2,'imperfective'), (45,'IRR',2,'irrealis'), (46,'LOC',2,'locative'), (47,'M',2,'masculine'), (48,'N',2,'neuter'), (49,'NEG',2,'negation, negative'), (50,'NMLZ',2,'nominalizer/nominalization'), (51,'NOM',2,'nominative'), (52,'OBL',2,'oblique'), (53,'PASS',2,'passive'), (54,'PFV',2,'perfective'), (55,'PL',2,'plural'), (56,'POSS',2,'possessive'), (57,'PPP',2,'past passive participle'), (58,'PRED',2,'predicative'), (59,'PRF',2,'perfect'), (60,'PRS',2,'present'), (61,'PROG',2,'progressive'), (62,'PROH',2,'prohibitive'), (63,'PROX',2,'proximal/proximate'), (64,'PST',2,'past'), (65,'PTCP',2,'participle'), (66,'PURP',2,'purposive'), (67,'Q',2,'question particle/marker'), (68,'QUOT',2,'quotative'), (69,'RECP',2,'reciprocal'), (70,'REFL',2,'reflexive'), (71,'REL',2,'relative'), (72,'RES',2,'resultative'), (73,'SBJV',2,'subjunctive'), (74,'SG',2,'singular'), (75,'TOP',2,'topic'), (76,'TR',2,'transitive'), (77,'VOC',2,'vocative');
INSERT INTO `word_annotation_type_choices` VALUES (78,'NOUN',3,'noun'), (79,'PRON',3,'pronoun'), (80,'VRB',3,'verb'), (81,'PTCP',3,'participle'), (82,'ADJ',3,'adjective'), (83,'ADV',3,'adverb'), (84,'ADP',3,'adposition'), (85,'CVB',3,'converb'), (86,'INF',3,'infinitive');
INSERT INTO `word_annotation_type_choices` VALUES (87,'A',4,'transitive subject'), (88,'S',4,'intransitive subject'), (89,'O',4,'object'), (90,'V',4,'verb');
INSERT INTO `word_annotation_type_choices` VALUES (91,'AG',5,'agent'), (92,'EXP',5,'experiencer'), (93,'REC',5,'recipient'), (94,'STIM',5,'stimulus'), (95,'TH',5,'theme'), (96,'PAT',5,'patient');
INSERT INTO `word_annotation_type_choices` VALUES(97,'TOP',6,'TOP');

INSERT INTO `sentence_annotation_types` VALUES (1,'add info','additional information'), (2,'english','translation into English');

INSERT INTO `languages` VALUES (1,'hi','Hindi');

INSERT INTO `roles` VALUES (1,'administrator'), (2,'editor'), (3,'reader');
