INSERT INTO `documents` VALUES (1,'Dokument testowy',3,1);

INSERT INTO `sentences` VALUES (1, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (1, 1, 'rājagṛha');
INSERT INTO `words` (id, sentence_id, text) VALUES (2, 1, 'nagari');
INSERT INTO `words` (id, sentence_id, text) VALUES (3, 1, 'śreṇika');
INSERT INTO `words` (id, sentence_id, text) VALUES (4, 1, 'rājā,');
INSERT INTO `words` (id, sentence_id, text) VALUES (5, 1, 'cillaṇā');
INSERT INTO `words` (id, sentence_id, text) VALUES (6, 1, 'paṭṭa-rājñī.');
INSERT INTO `words` (id, sentence_id, text) VALUES (7, 1, 'teha-hnaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (8, 1, 'eka-stabha-');
INSERT INTO `sentences` VALUES (2, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (9, 2, 'āvāsa-nu');
INSERT INTO `words` (id, sentence_id, text) VALUES (10, 2, 'ḍohalu');
INSERT INTO `words` (id, sentence_id, text) VALUES (11, 2, 'ūpanu');
INSERT INTO `words` (id, sentence_id, text) VALUES (12, 2, 'te');
INSERT INTO `words` (id, sentence_id, text) VALUES (13, 2, 'abhayakumāriṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (14, 2, 'dewatā');
INSERT INTO `words` (id, sentence_id, text) VALUES (15, 2, 'owarādhī');
INSERT INTO `words` (id, sentence_id, text) VALUES (16, 2, 'teha');
INSERT INTO `words` (id, sentence_id, text) VALUES (17, 2, 'pāhiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (18, 2, 'sarvartuka-vana');
INSERT INTO `sentences` VALUES (3, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (19, 3, 'sahita');
INSERT INTO `words` (id, sentence_id, text) VALUES (20, 3, 'eka');
INSERT INTO `words` (id, sentence_id, text) VALUES (21, 3, 'stabha-āwāsa');
INSERT INTO `words` (id, sentence_id, text) VALUES (22, 3, 'karāwī');
INSERT INTO `words` (id, sentence_id, text) VALUES (23, 3, 'pūriu.');
INSERT INTO `sentences` VALUES (4, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (24, 4, 'isiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (25, 4, 'eka');
INSERT INTO `words` (id, sentence_id, text) VALUES (26, 4, 'mātanga-nai');
INSERT INTO `words` (id, sentence_id, text) VALUES (27, 4, 'kaḷatra-hnai');
INSERT INTO `words` (id, sentence_id, text) VALUES (28, 4, 'akāḷi');
INSERT INTO `words` (id, sentence_id, text) VALUES (29, 4, 'āmbā-nuṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (30, 4, 'ḍohalu');
INSERT INTO `words` (id, sentence_id, text) VALUES (31, 4, 'ūpanu.');
INSERT INTO `words` (id, sentence_id, text) VALUES (32, 4, 'tīṇaiṃ');
INSERT INTO `sentences` VALUES (5, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (33, 5, 'mātangiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (34, 5, 'awanāminī');
INSERT INTO `words` (id, sentence_id, text) VALUES (35, 5, 'vidyā-naiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (36, 5, 'bi');
INSERT INTO `words` (id, sentence_id, text) VALUES (37, 5, 'sarvartuka');
INSERT INTO `words` (id, sentence_id, text) VALUES (38, 5, 'vana-nā');
INSERT INTO `words` (id, sentence_id, text) VALUES (39, 5, 'āmbā-nī');
INSERT INTO `words` (id, sentence_id, text) VALUES (40, 5, 'ḍāḷa');
INSERT INTO `words` (id, sentence_id, text) VALUES (41, 5, 'namāṛī');
INSERT INTO `words` (id, sentence_id, text) VALUES (42, 5, 'āmbā');
INSERT INTO `sentences` VALUES (6, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (43, 6, 'leī');
INSERT INTO `words` (id, sentence_id, text) VALUES (44, 6, 'ḍohalu');
INSERT INTO `words` (id, sentence_id, text) VALUES (45, 6, 'pūriu.');
INSERT INTO `sentences` VALUES (7, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (46, 7, 'te');
INSERT INTO `words` (id, sentence_id, text) VALUES (47, 7, 'āmbā-nu');
INSERT INTO `words` (id, sentence_id, text) VALUES (48, 7, 'cora');
INSERT INTO `words` (id, sentence_id, text) VALUES (49, 7, 'abhayakumāriṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (50, 7, 'bṛhat-kumārī-nī');
INSERT INTO `words` (id, sentence_id, text) VALUES (51, 7, 'kathā');
INSERT INTO `words` (id, sentence_id, text) VALUES (52, 7, 'kahī');
INSERT INTO `words` (id, sentence_id, text) VALUES (53, 7, 'buddhi-naiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (54, 7, 'baḷi');
INSERT INTO `sentences` VALUES (8, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (55, 8, 'pragaṭa');
INSERT INTO `words` (id, sentence_id, text) VALUES (56, 8, 'kīdhu');
INSERT INTO `words` (id, sentence_id, text) VALUES (57, 8, 'teha-hnai');
INSERT INTO `words` (id, sentence_id, text) VALUES (58, 8, 'śreṇika-rāiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (59, 8, 'kahiu-jai');
INSERT INTO `words` (id, sentence_id, text) VALUES (60, 8, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (61, 8, 'dii,');
INSERT INTO `words` (id, sentence_id, text) VALUES (62, 8, 'tu');
INSERT INTO `words` (id, sentence_id, text) VALUES (63, 8, 'mūkauṃ.');
INSERT INTO `sentences` VALUES (9, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (64, 9, 'tīṇaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (65, 9, 'māniu.');
INSERT INTO `sentences` VALUES (10, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (66, 10, 'śreṇika');
INSERT INTO `words` (id, sentence_id, text) VALUES (67, 10, 'siṃhāsaṇi');
INSERT INTO `words` (id, sentence_id, text) VALUES (68, 10, 'baiṭhau');
INSERT INTO `words` (id, sentence_id, text) VALUES (69, 10, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (70, 10, 'paḍhai');
INSERT INTO `words` (id, sentence_id, text) VALUES (71, 10, 'ghaṇī');
INSERT INTO `words` (id, sentence_id, text) VALUES (72, 10, 'vāri');
INSERT INTO `words` (id, sentence_id, text) VALUES (73, 10, 'mātangiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (74, 10, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (75, 10, 'kahī,');
INSERT INTO `words` (id, sentence_id, text) VALUES (76, 10, 'puṇa');
INSERT INTO `sentences` VALUES (11, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (77, 11, 'āvai');
INSERT INTO `words` (id, sentence_id, text) VALUES (78, 11, 'nahīṃ.');
INSERT INTO `words` (id, sentence_id, text) VALUES (79, 11, 'abhayakumāriṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (80, 11, 'kahiu-mātanga-hnaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (81, 11, 'siṃhāsani');
INSERT INTO `words` (id, sentence_id, text) VALUES (82, 11, 'baisāri');
INSERT INTO `words` (id, sentence_id, text) VALUES (83, 11, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (84, 11, 'lio');
INSERT INTO `sentences` VALUES (12, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (85, 12, 'tu');
INSERT INTO `words` (id, sentence_id, text) VALUES (86, 12, 'āvai');
INSERT INTO `words` (id, sentence_id, text) VALUES (87, 12, 'pachai');
INSERT INTO `words` (id, sentence_id, text) VALUES (88, 12, 'mātanga');
INSERT INTO `words` (id, sentence_id, text) VALUES (89, 12, 'siṃhāsani');
INSERT INTO `words` (id, sentence_id, text) VALUES (90, 12, 'baisarī');
INSERT INTO `words` (id, sentence_id, text) VALUES (91, 12, 'be');
INSERT INTO `words` (id, sentence_id, text) VALUES (92, 12, 'hātha');
INSERT INTO `words` (id, sentence_id, text) VALUES (93, 12, 'joṛī');
INSERT INTO `words` (id, sentence_id, text) VALUES (94, 12, 'śreṇika');
INSERT INTO `words` (id, sentence_id, text) VALUES (95, 12, 'mahā-rāya');
INSERT INTO `words` (id, sentence_id, text) VALUES (96, 12, 'āgaḷi');
INSERT INTO `sentences` VALUES (13, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (97, 13, 'ūbhu');
INSERT INTO `words` (id, sentence_id, text) VALUES (98, 13, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (99, 13, 'lii.');
INSERT INTO `words` (id, sentence_id, text) VALUES (100, 13, 'eka');
INSERT INTO `words` (id, sentence_id, text) VALUES (101, 13, 'vāra-nī');
INSERT INTO `words` (id, sentence_id, text) VALUES (102, 13, 'paḍhī');
INSERT INTO `words` (id, sentence_id, text) VALUES (103, 13, 'te');
INSERT INTO `words` (id, sentence_id, text) VALUES (104, 13, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (105, 13, 'āwī.');
INSERT INTO `words` (id, sentence_id, text) VALUES (106, 13, 'ima');
INSERT INTO `words` (id, sentence_id, text) VALUES (107, 13, 'anere-ū');
INSERT INTO `words` (id, sentence_id, text) VALUES (108, 13, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (109, 13, 'lete');
INSERT INTO `sentences` VALUES (14, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (110, 14, 'vinaya');
INSERT INTO `words` (id, sentence_id, text) VALUES (111, 14, 'karivu');
INSERT INTO `sentences` VALUES (15, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (112, 15, 'eka');
INSERT INTO `words` (id, sentence_id, text) VALUES (113, 15, 'nāpita');
INSERT INTO `words` (id, sentence_id, text) VALUES (114, 15, 'vidyā-naiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (115, 15, 'baḷi');
INSERT INTO `words` (id, sentence_id, text) VALUES (116, 15, 'āpaṇau');
INSERT INTO `words` (id, sentence_id, text) VALUES (117, 15, 'charapalu');
INSERT INTO `words` (id, sentence_id, text) VALUES (118, 15, 'ākāśa-maṇḍaḷi');
INSERT INTO `words` (id, sentence_id, text) VALUES (119, 15, 'rākhai');
INSERT INTO `words` (id, sentence_id, text) VALUES (120, 15, 'te');
INSERT INTO `sentences` VALUES (16, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (121, 16, 'kanhai');
INSERT INTO `words` (id, sentence_id, text) VALUES (122, 16, 'ekai');
INSERT INTO `words` (id, sentence_id, text) VALUES (123, 16, 'tridaṇḍii');
INSERT INTO `words` (id, sentence_id, text) VALUES (124, 16, 'te');
INSERT INTO `words` (id, sentence_id, text) VALUES (125, 16, 'vidyā');
INSERT INTO `words` (id, sentence_id, text) VALUES (126, 16, 'līdhī');
INSERT INTO `words` (id, sentence_id, text) VALUES (127, 16, 'tridaṇḍiu');
INSERT INTO `words` (id, sentence_id, text) VALUES (128, 16, 'videśii');
INSERT INTO `words` (id, sentence_id, text) VALUES (129, 16, 'jai');
INSERT INTO `words` (id, sentence_id, text) VALUES (130, 16, 'tīṇi');
INSERT INTO `words` (id, sentence_id, text) VALUES (131, 16, 'vidyāiṃ');
INSERT INTO `sentences` VALUES (17, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (132, 17, 'āpaṇā');
INSERT INTO `words` (id, sentence_id, text) VALUES (133, 17, 'tridaṇḍa');
INSERT INTO `words` (id, sentence_id, text) VALUES (134, 17, 'ākāśa-maṇḍaḷi');
INSERT INTO `words` (id, sentence_id, text) VALUES (135, 17, 'rākhai');
INSERT INTO `words` (id, sentence_id, text) VALUES (136, 17, 'te');
INSERT INTO `words` (id, sentence_id, text) VALUES (137, 17, 'dekhī');
INSERT INTO `words` (id, sentence_id, text) VALUES (138, 17, 'vismaya');
INSERT INTO `words` (id, sentence_id, text) VALUES (139, 17, 'hūntu');
INSERT INTO `words` (id, sentence_id, text) VALUES (140, 17, 'loka');
INSERT INTO `words` (id, sentence_id, text) VALUES (141, 17, 'teha-hnaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (142, 17, 'pūjā-');
INSERT INTO `sentences` VALUES (18, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (143, 18, 'bhakti');
INSERT INTO `words` (id, sentence_id, text) VALUES (144, 18, 'karaiṃ.');
INSERT INTO `sentences` VALUES (19, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (145, 19, 'eka');
INSERT INTO `words` (id, sentence_id, text) VALUES (146, 19, 'vāra');
INSERT INTO `words` (id, sentence_id, text) VALUES (147, 19, 'loke');
INSERT INTO `words` (id, sentence_id, text) VALUES (148, 19, 'pūchiuṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (149, 19, '-');
INSERT INTO `words` (id, sentence_id, text) VALUES (150, 19, 'e');
INSERT INTO `words` (id, sentence_id, text) VALUES (151, 19, 'vidyā-nau');
INSERT INTO `words` (id, sentence_id, text) VALUES (152, 19, 'tumhāraiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (153, 19, 'guru');
INSERT INTO `words` (id, sentence_id, text) VALUES (154, 19, 'kuṇa?');
INSERT INTO `words` (id, sentence_id, text) VALUES (155, 19, 'tīṇaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (156, 19, 'lājataiṃ');
INSERT INTO `sentences` VALUES (20, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (157, 20, 'nāpita');
INSERT INTO `words` (id, sentence_id, text) VALUES (158, 20, 'na');
INSERT INTO `words` (id, sentence_id, text) VALUES (159, 20, 'kahiu');
INSERT INTO `words` (id, sentence_id, text) VALUES (160, 20, 'ima');
INSERT INTO `words` (id, sentence_id, text) VALUES (161, 20, 'kahiuṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (162, 20, '-himavanta-vāsī');
INSERT INTO `words` (id, sentence_id, text) VALUES (163, 20, 'māharu');
INSERT INTO `words` (id, sentence_id, text) VALUES (164, 20, 'vidyā-nu');
INSERT INTO `words` (id, sentence_id, text) VALUES (165, 20, 'guru');
INSERT INTO `words` (id, sentence_id, text) VALUES (166, 20, 'tīṇaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (167, 20, 'guru-');
INSERT INTO `sentences` VALUES (21, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (168, 21, 'naiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (169, 21, 'olawiwaiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (170, 21, 'karī');
INSERT INTO `words` (id, sentence_id, text) VALUES (171, 21, 'tridaṇḍa');
INSERT INTO `words` (id, sentence_id, text) VALUES (172, 21, 'khaṛakhaṛāṭa');
INSERT INTO `words` (id, sentence_id, text) VALUES (173, 21, 'karatauṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (174, 21, 'bhuṃiṃ');
INSERT INTO `words` (id, sentence_id, text) VALUES (175, 21, 'paḍiuṃ.');
INSERT INTO `words` (id, sentence_id, text) VALUES (176, 21, 'loke');
INSERT INTO `words` (id, sentence_id, text) VALUES (177, 21, 'sahūe');
INSERT INTO `words` (id, sentence_id, text) VALUES (178, 21, 'hasiuṃ');
INSERT INTO `sentences` VALUES (22, 1);
INSERT INTO `words` (id, sentence_id, text) VALUES (179, 22, 'teha');
INSERT INTO `words` (id, sentence_id, text) VALUES (180, 22, 'bhaṇī');
INSERT INTO `words` (id, sentence_id, text) VALUES (181, 22, 'bīja');
INSERT INTO `words` (id, sentence_id, text) VALUES (182, 22, '(bīje-ū)');
INSERT INTO `words` (id, sentence_id, text) VALUES (183, 22, 'guru-nau');
INSERT INTO `words` (id, sentence_id, text) VALUES (184, 22, 'nihnawa');
INSERT INTO `words` (id, sentence_id, text) VALUES (185, 22, 'na');
INSERT INTO `words` (id, sentence_id, text) VALUES (186, 22, 'karivu.');
INSERT INTO `sentences` VALUES (23, 1);
